# Определяем собственное исключение
class UnknownException(Exception):
    pass